sudo: false
language: node_js
node_js:
  - "14"
  - "12"
  - "10"
matrix:
  fast_finish: true
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never

before_script: "npm run linter"
script: "npm run test"
after_script: "npm run coverage"
